name: First Workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print messages
        run: |
          echo "Hello World"
          echo "Hello Picklu"
     
  
